web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./nginx/conf.d/:/etc/nginx/conf.d/
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/proxy.conf:/etc/nginx/proxy.conf
        - ~/laravel:/var/www/laravel
    links:
        - php7
php7:
    build: ./php7
    volumes:
        - ~/laravel:/var/www/laravel
        - ~/docker-data/php7/conf.d:/usr/local/etc/php/conf.d
    links:
        - mysql
mysql:
    image: mysql:5.7
    ports:
        - "3306:3306"
    env_file:
        - .mysql.env 
    volumes:
        - ~/docker-data/mysql/data:/var/lib/mysql
        - ~/docker-data/mysql/conf.d:/etc/mysql/conf.d
